"""added jobs models

Revision ID: 2992adc43afe
Revises: 804a15559e7a
Create Date: 2025-05-27 12:39:19.608563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2992adc43afe'
down_revision = '804a15559e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_position_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_job_applications_job_position_id', 'job_positions', ['job_position_id'], ['id'])
        batch_op.drop_column('job_title')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint('fk_job_applications_job_position_id', type_='foreignkey')
        batch_op.drop_column('job_position_id')

    # ### end Alembic commands ###
