"""added some chat helpers

Revision ID: 736b48dc188d
Revises: a20a1e7b1acd
Create Date: 2025-05-28 17:50:52.259181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736b48dc188d'
down_revision = 'a20a1e7b1acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('read_at')
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
